name: 'Terraform Init Setup'
description: 'Performs Terraform Init with S3 Backend'

inputs:
  bucket:
    required: true
    description: 'S3 backend bucket'
  key:
    required: true
    description: 'S3 backend key'
  region:
    required: true
    description: 'AWS region'

outputs:
  key:
    description: 'S3 backend key used for Terraform State'
    value: ${{ inputs.key }}

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.bucket }}" \
          -backend-config="key=${{ inputs.key }}" \
          -backend-config="region=${{ inputs.region }}" \
          -backend-config="encrypt=true" \
          -backend-config="use_lockfile=true"
      working-directory: ./terraform
      shell: bash

