name: "S3 React App Deploy"
description: "Build and deploy React app to S3 and optionally invalidate CloudFront"

inputs:
  bucket:
    required: true
    description: "S3 bucket to deploy to"
  region:
    required: true
    description: "AWS region"
  dist_dir:
    required: false
    default: "dist"
    description: "React app build output directory"
  build_command:
    required: false
    default: "npm run build"
    description: "Command to build the React app"

  distribution_id:
    required: false
    description: "Optional CloudFront distribution ID to invalidate"

  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true

secrets:
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm ci

    - name: Build React App
      run: ${{ inputs.build_command }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ inputs.region }}

    - name: Upload to S3
      run: aws s3 sync ${{ inputs.dist_dir }} s3://${{ inputs.bucket }} --delete

    - name: Invalidate CloudFront Cache
      if: ${{ inputs.distribution_id != '' }}
      run: |
        echo "Invalidating CloudFront cache for distribution: ${{ inputs.distribution_id }}"
        aws cloudfront create-invalidation \
          --distribution-id ${{ inputs.distribution_id }} \
          --paths "/*"

