name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm resource destruction'
        required: true

env:
  CONFIG_DIRECTORY: ./terraform
  STATE_BUCKET: tf-state-bucket
  PROJECT_NAME: tf-project
  AWS_REGION: us-east-1
  VAR_FILE: terraform.tfvars.development

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      content: write
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
      - name: Terraform Destroy
        uses: mleager/tf-shared-actions/.github/actions/terraform-destroy@main
        with:
          bucket: ${{ env.STATE_BUCKET }}
          key: ${{ env.PROJECT_NAME }}/terraform.tfstate
          region: ${{ env.AWS_REGION }}
          var_file: ${{ env.VAR_FILE }}
          confirm_destroy: ${{ github.event.inputs.confirm_destroy }}
          make_commit_comment: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

