name: Terraform Plan

on:
  pull_request:
    branches:
      - main

env:
  STATE_BUCKET: tf-state-8864
  PROJECT_NAME: tf-s3-global-state

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Terraform Plan Setup
        id: terraform-plan
        uses: mleager/tf-shared-actions/.github/actions/terraform-plan@main
        with:
          bucket: ${{ env.STATE_BUCKET }}
          key: ${{ env.PROJECT_NAME }}/terraform.tfstate
          region: ${{ vars.AWS_REGION }}
          var_file: terraform.tfvars.development

      # - name: Backend Key Output
      #   run: |
      #     echo "Used key: ${{ steps.terraform-plan.outputs.key }}"

      - name: Post Terraform Plan as PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const planOutput = require('fs').readFileSync('./terraform/plan.txt', 'utf8');

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## Terraform Plan

              <details><summary>Show Plan</summary>

              \`\`\`hcl
              ${planOutput}
              \`\`\`

              </details>`
            });

