name: Infra and Frontend Deploy

on:
  push:
    branches:
      - main

env:
  STATE_BUCKET: tf-state-bucket
  PROJECT_NAME: tf-project
  AWS_REGION: us-east-1
  VAR_FILE: terraform.tfvars.development
  ENVIRONMENT: development
  S3_BUCKET: react-app-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    # - name: Set OIDC Role Name
    #   run: echo "OIDC_ROLE=oidc-${{ github.event.repository.name }}-${{ env.ENVIRONMENT }}-apply" >> $GITHUB_ENV

    - name: Terraform Apply
      id: apply
      uses: mleager/tf-shared-actions/.github/actions/terraform-apply@main
      with:
        create_oidc_role: false
        oidc_role: oidc-role-name
        aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        project_name: ${{ env.PROJECT_NAME }}
        environment: ${{ env.ENVIRONMENT }}
        bucket: ${{ env.STATE_BUCKET }}
        key: ${{ env.PROJECT_NAME }}/terraform.tfstate
        region: ${{ env.AWS_REGION }}
        var_file: terraform.tfvars.${{ env.ENVIRONMENT }}
        make_pr_comment: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # oidc_role: ${{ env.OIDC_ROLE }}

    - name: Get CloudFront Distribution ID (Optional)
      id: tf-outputs
      run: |
        DIST_ID=$(terraform -chdir=./terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")
        echo "dist_id=$DIST_ID" >> $GITHUB_OUTPUT

    - name: Deploy React App to S3
      uses: mleager/tf-shared-actions/.github/actions/s3-deploy@main
      with:
        create_oidc_role: false
        oidc_role: oidc-role-name
        aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        project_name: ${{ env.PROJECT_NAME }}
        environment: ${{ env.ENVIRONMENT }}
        bucket: ${{ env.S3_BUCKET }}
        region: ${{ env.AWS_REGION }}
        distribution_id: ${{ steps.tf-outputs.outputs.dist_id }}
        # oidc_role: ${{ env.OIDC_ROLE }}

