name: 'Terraform Plan Setup'
description: 'Performs Terraform setup, init, validate, plan with S3 backend'

inputs:
  bucket:
    description: 'S3 backend bucket'
    required: false
    default: 'tf-state-8864'
  key:
    description: 'S3 backend key'
    required: true
  region:
    description: 'AWS region'
    required: true
  var_file:
    description: 'Terraform var file'
    required: false
    default: 'terraform.tfvars.development'
  tf_version:
    description: 'Terraform version'
    required: false
    default: '1.12.1'
  aws_access_key_id:
    required: true
    description: 'AWS access key ID'
  aws_secret_access_key:
    required: true
    description: 'AWS secret access key'

outputs:
  key:
    description: 'S3 backend key used for Terraform State'
    value: ${{ inputs.key }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf_version }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.region }}

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./terraform
      shell: bash

    - name: Terraform Init with S3 Backend
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.bucket }}" \
          -backend-config="key=${{ inputs.key }}" \
          -backend-config="region=${{ inputs.region }}" \
          -backend-config="encrypt=true" \
          -backend-config="use_lockfile=true"
      shell: bash

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform
      shell: bash

    - name: Terraform Plan (Binary)
      run: terraform plan -var-file=${{ inputs.var_file }} -out=tfplan
      working-directory: ./terraform
      shell: bash

    - name: Terraform Show (Readable Plan to plan.txt)
      run: terraform show -no-color tfplan | tee plan.txt
      working-directory: ./terraform
      shell: bash

